import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";

const djingo = localFont({
  src: [
    {
      path: "../public/fonts/Djingo-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-djingo",
});

const helveticaNeue = localFont({
  src: [
    {
      path: "../public/fonts/HelveticaNeue-Roman.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-neue",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${djingo.variable} ${helveticaNeue.variable}`}>
      <body style={{ fontFamily: "var(--font-helvetica-neue)" }}>
        <Header/>
        {children}
        
        </body>
    </html>
  );
}
