import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import LenisProvider from "./components/LenisProvider";
import { League_Spartan } from "next/font/google";

// const djingo = localFont({
//   src: [
//     {
//       path: "../public/fonts/Djingo-Regular.ttf",
//       weight: "400",
//       style: "normal",
//     },
//   ],
//   variable: "--font-league-spartan",
// });

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-league-spartan",
});

const helveticaNeue = localFont({
  src: [
    {
      path: "../public/fonts/HelveticaNeue-Roman.ttf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-neue",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${leagueSpartan.variable} ${helveticaNeue.variable}`}>
      <body style={{ fontFamily: "var(--font-helvetica-neue)" }}>
        <div className="noise-bg"></div>
        <LenisProvider>
        <Header/>
        {children}
        <Footer/>
        </LenisProvider>
        </body>
    </html>
  );
}
